name: Download and Commit EXE
    on:
      workflow_dispatch:
    jobs:
      download-and-commit:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4 # می‌تونیم همین v4 رو نگه داریم، چون commit-files خودش مدیریت می‌کنه

          - name: Download Lunacy EXE from URL
            run: curl -L "https://lcdn.icons8.com/setup/LunacySetup.exe" -o LunacySetup.exe

          - name: Commit and push the file
            uses: EndBug/commit-files@v4 # این اکشن جدید رو استفاده می‌کنیم
            with:
              add: 'LunacySetup.exe' # فایلی که می‌خوایم اضافه کنیم
              commit_message: 'Add LunacySetup.exe from URL'
              repository: ${{ github.repository }}
              token: ${{ secrets.GITHUB_TOKEN }}
